apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-service
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/thomasvitale/springio/web-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
